import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// component
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full bg-gray-50`}>
        <header className="sticky top-0 z-50 h-full w-full overflow-hidden">
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
